using Dates

"""
This function takes atoms, their coordinates, box definition and data within this box and writes a gaussian cube file https://paulbourke.net/dataformats/cube/
Keep in mind, that this does NOT include the complete definition of cube files but is rather oriented to suit the EntMix.jl needs.

#### Args:
  - filename (str): name of the file to write
  - atoms (Array{Int}): array of atom element numbers
  - coords (Array{Float64}): array of coordinates of atoms
  - box (Array{Float64}): box definition with axis vectors (3x3 matrix)
  - repetitions (Vector{Int}): number of repetitions in each direction (na, nb, nc)
  - origin (Vector{Float64}): origin of the box
  - data (Array{Float64}, (na, nb, nc)): data within the box at each grid point along the axes vectors

#### Optional:
  - atomcharges (Array{Float64}): array of atom charges defaults to zeros
  - mode (str): write mode, default is "a" options are "w"rite and "a"ppend
  - comment1 (str): comment line 1
  - comment2 (str): comment line 2
  - inputunits (str): input units, default is "AU" options are "AU" (atomic units) and "ANG" (angstroem)
"""
function write_cube(filename, atoms, coords, box, repetitions, origin, data; mode="a", comment1="generated by EntMix.jl on $(round(now(), Dates.Second))", comment2="Mixing Entropy distribution ", atomcharges=zeros(length(atoms)), inputunits="AU")
    if inputunits == "ANG"
        # convert to atomic units
        origin = origin ./ 0.529177
        box = box ./ 0.529177
        coords = coords ./ 0.529177
    elseif inputunits != "AU"
        @error "inputunits should be either 'AU' or 'ANG'"
        exit(1)
    end
    separator = "   "
    fio = open(filename, mode*"+")
    ##############
    # write header
    ##############
    # comments
    print(fio, "# ", comment1, "\n")
    print(fio, "# ", comment2, "\n")
    # number of atoms and origin
    print(fio, length(atoms), separator, origin[1], separator, origin[2], separator, origin[3], "\n")
    # voxels defined by axis vectors and their repetitions
    for i in 1:3
        print(fio, repetitions[i], separator, box[i, 1], separator, box[i, 2], separator, box[i, 3], "\n")
    end
    # atoms and their coordinates and charges
    for i in 1:length(atoms)
        print(fio, atoms[i], separator, atomcharges[i], separator, coords[i, 1], separator, coords[i, 2], separator, coords[i, 3], "\n")
    end

    # data
    separator = " "
    for i in 1:size(data, 1)
        for j in 1:size(data, 2)
            for k in 1:size(data, 3)
                print(fio, data[i, j, k], separator)
                if k % 6 == 0
                    print(fio, "\n")
                end
            end
        end
    end
    skip(fio, -1)
    if read(fio)[1] != 0x0a  # this represents the linebreak char
        print(fio, "\n")
    end
    close(fio)
end

"""
this function creates a gaussian cube file compatible grid.

#### Args:
* box (Matrix{Float64}): box consisting of cube vectors
* repetitions (Vector{Int}): number of repetitions in each direction (na, nb, nc)
* origin (Vector{Float64}): origin of the grid
"""
function create_grid(box, repetitions, origin)
    # grid based on box and n1, n2, n3 and origin
    n1, n2, n3 = repetitions
    v1 , v2, v3 = eachrow(box) 
    @debug v1,v2,v3
    grid = [
        origin .+ i*v1 + j*v2 + k*v3 for i in 0:n1-1, j in 0:n2-1, k in 0:n3-1
    ]
    return grid
end

"""
Evaluates a function at each point of a cube grid and returns the results in a new array.

#### Args:
    grid: The cube grid array (n1 x n2 x n3 array of vectors)
    f: Function that takes a vector as input and returns a scalar
    
#### Returns:
    Array{Float64} with dimensions matching the input grid
"""
function evaluate_on_grid(grid, f)
    n1, n2, n3 = size(grid)
    result = zeros(n1, n2, n3)
    
    for i in 1:n1
        for j in 1:n2
            for k in 1:n3
                result[i,j,k] = f(grid[i,j,k])
            end
        end
    end
    
    return result
end

# Example usage:
# grid = create_grid(v1, v2, v3, 40, 40, 40, origin)
# # Define a function to evaluate at each point
# f(v) = sum(v.^2)  # Example: calculates squared distance from origin
# result = evaluate_on_grid(grid, f)
